{{
  config(
    materialized = 'table',
    as_columnstore = false
    )
}}

select  
STG_CHEQUE.DATE_CHEQUE,
s.id_contractor, 
s.contractor_name,
STG_GOODS_NAMES.NM,
STG_CHEQUE_ITEM.QUANTITY*STG_SCALING_RATIO.SCALING_K as QUANTITY,
STG_CHEQUE_ITEM.SUMM_DISCOUNT,
STG_CHEQUE_ITEM.PRICE_SUP*STG_CHEQUE_ITEM.QUANTITY as SUM_SUPPLIER,
STG_CHEQUE_ITEM.PRICE_SAL*STG_CHEQUE_ITEM.QUANTITY as SUM_SAL


from 
STG_CHEQUE, STG_CHEQUE_ITEM, STG_GOODS_NAMES, STG_SCALING_RATIO, {{ ref('store') }} as s
where STG_CHEQUE.ID_CHEQUE_GLOBAL = STG_CHEQUE_ITEM.ID_CHEQUE_GLOBAL
and STG_CHEQUE_ITEM.ID_SCALING_RATIO = STG_SCALING_RATIO.ID_SCALING_RATIO
and STG_CHEQUE_ITEM.ID_GOODS = STG_GOODS_NAMES.ID_GOODS
and STG_CHEQUE_ITEM.id_store = s.id_store
and STG_CHEQUE.DOCUMENT_STATE !='DEL' --- есть удаленные чеки которые не нужно учитывать