USE [master]
GO

/****** Object:  Database [zakaz]    Script Date: 25.01.2022 7:14:24 ******/
CREATE DATABASE [zakaz]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'zakaz', FILENAME = N'D:\DATABASES\Database_efarma\zakaz.mdf' , SIZE = 148608KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'zakaz_log', FILENAME = N'D:\DATABASES\Database_efarma\zakaz_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [zakaz] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [zakaz].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [zakaz] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [zakaz] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [zakaz] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [zakaz] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [zakaz] SET ARITHABORT OFF 
GO

ALTER DATABASE [zakaz] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [zakaz] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [zakaz] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [zakaz] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [zakaz] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [zakaz] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [zakaz] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [zakaz] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [zakaz] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [zakaz] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [zakaz] SET  DISABLE_BROKER 
GO

ALTER DATABASE [zakaz] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [zakaz] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [zakaz] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [zakaz] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [zakaz] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [zakaz] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [zakaz] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [zakaz] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [zakaz] SET  MULTI_USER 
GO

ALTER DATABASE [zakaz] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [zakaz] SET DB_CHAINING OFF 
GO

ALTER DATABASE [zakaz] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [zakaz] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [zakaz] SET  READ_WRITE 
GO

USE [zakaz]
GO

/****** Object:  View [dbo].[STG_CHEQUE]    Script Date: 25.01.2022 7:16:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[STG_CHEQUE]
AS
SELECT        ID_CHEQUE, ID_CHEQUE_GLOBAL, DATE_MODIFIED, DATE_CHEQUE, DOCUMENT_STATE, CHEQUE_TYPE, SUMM, SUM_DISCOUNT, PAY_TYPE_NAME
FROM            eplus_work.dbo.CHEQUE AS wuth WITH (nolock)
WHERE        (DATE_CHEQUE > GETDATE() - 60)

GO

CREATE VIEW [dbo].[STG_CHEQUE_ITEM]
AS
SELECT        eplus_work.dbo.CHEQUE_ITEM.ID_GOODS, eplus_work.dbo.CHEQUE_ITEM.ID_SCALING_RATIO, eplus_work.dbo.CHEQUE_ITEM.QUANTITY, eplus_work.dbo.CHEQUE_ITEM.PRICE, 
                         eplus_work.dbo.CHEQUE_ITEM.SUMM_DISCOUNT, eplus_work.dbo.CHEQUE_ITEM.SUMM, eplus_work.dbo.LOT.PRICE_SUP, eplus_work.dbo.LOT.PRICE_SAL, 
                         eplus_work.dbo.CHEQUE_ITEM.ID_CHEQUE_GLOBAL, eplus_work.dbo.LOT.ID_STORE
FROM            eplus_work.dbo.CHEQUE_ITEM INNER JOIN
                         eplus_work.dbo.LOT ON eplus_work.dbo.LOT.ID_LOT_GLOBAL = eplus_work.dbo.CHEQUE_ITEM.ID_LOT_GLOBAL
WHERE        (eplus_work.dbo.CHEQUE_ITEM.ID_CHEQUE_GLOBAL IN
                             (SELECT        ID_CHEQUE_GLOBAL
                               FROM            eplus_work.dbo.CHEQUE
                               WHERE        (DATE_CHEQUE > GETDATE() - 60)))

GO

CREATE VIEW [dbo].[STG_CONTRACTOR]
AS
SELECT        ID_CONTRACTOR, NAME AS contractor_name
FROM            eplus_work.dbo.CONTRACTOR WITH (nolock)

GO

CREATE VIEW [dbo].[STG_GOODS_NAMES]
AS
SELECT        ID_GOODS, NM, NAME, PRODUCER
FROM            eplus_work.dbo.V_GOODS_NAMES

GO

CREATE VIEW [dbo].[STG_INVOICE]
AS
SELECT        ID_INVOICE_GLOBAL, ID_STORE, DOCUMENT_STATE, ID_CONTRACTOR_SUPPLIER AS id_contractor,
 DOCUMENT_DATE, SUM_SUPPLIER, SUM_RETAIL, DATE_MODIFIED, INCOMING_DATE, INCOMING_NUMBER, 
                         ON_THE_WAY
FROM            eplus_work.dbo.INVOICE WITH (nolock)
WHERE        (DOCUMENT_DATE > GETDATE() - 60)

GO
CREATE VIEW [dbo].[STG_INVOICE_ITEM]
AS
SELECT        ID_INVOICE_GLOBAL, ID_GOODS, ID_SCALING_RATIO, QUANTITY, SUPPLIER_PRICE_VAT, SUPPLIER_SUM_VAT, RETAIL_PRICE_VAT, RETAIL_SUM_VAT
FROM            eplus_work.dbo.INVOICE_ITEM
WHERE        (ID_INVOICE_GLOBAL IN
                             (SELECT        ID_INVOICE_GLOBAL
                               FROM            eplus_work.dbo.INVOICE
                               WHERE        (DOCUMENT_DATE > GETDATE() - 60)))

GO

CREATE VIEW [dbo].[STG_REMAINS]
AS
SELECT        ID_LOT_GLOBAL, ID_GOODS, 
ID_STORE, ID_SCALING_RATIO, QUANTITY_REM,
 QUANTITY_RES, PRICE_SUP, PRICE_SAL,
  INVOICE_SOURCE, DOC_NUM, DOC_DATE,
   INCOMING_NUM, INCOMING_DATE, 
                         DATE_MODIFIED
FROM            eplus_work.dbo.LOT
WHERE        (QUANTITY_REM > 0)

GO

CREATE VIEW [dbo].[STG_SCALING_RATIO]
AS
SELECT        ID_SCALING_RATIO, NUMERATOR, DENOMINATOR,
 CAST(NUMERATOR AS decimal) / CAST(DENOMINATOR AS decimal) AS SCALING_K, ID_GOODS
FROM            eplus_work.dbo.SCALING_RATIO

GO

CREATE VIEW [dbo].[STG_STORE]
AS
SELECT        ID_STORE, NAME AS store_name, ID_CONTRACTOR
FROM            eplus_work.dbo.STORE WITH (nolock)

GO
